// Code generated by controller-gen equivalent. Hand-written to keep the tree
// buildable without controller-gen in CI. Regenerate with `make generate`.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// ---------- SecretKeySelector ----------

func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) { *out = *in }
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// ---------- StorageSpec ----------

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.StorageClassName != nil {
		s := *in.StorageClassName
		out.StorageClassName = &s
	}
	if in.AccessModes != nil {
		out.AccessModes = make([]corev1.PersistentVolumeAccessMode, len(in.AccessModes))
		copy(out.AccessModes, in.AccessModes)
	}
}

// ---------- AIConfig ----------

func (in *AIConfig) DeepCopyInto(out *AIConfig) {
	*out = *in
	if in.OpenAIAPIKeySecretRef != nil {
		out.OpenAIAPIKeySecretRef = in.OpenAIAPIKeySecretRef.DeepCopy()
	}
	if in.LLMOpenAIKeySecretRef != nil {
		out.LLMOpenAIKeySecretRef = in.LLMOpenAIKeySecretRef.DeepCopy()
	}
}

// ---------- ReplicationSpec ----------

func (in *ReplicationSpec) DeepCopyInto(out *ReplicationSpec) { *out = *in }

// ---------- RegionSpec ----------

func (in *RegionSpec) DeepCopyInto(out *RegionSpec) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.Tolerations != nil {
		out.Tolerations = make([]corev1.Toleration, len(in.Tolerations))
		for i := range in.Tolerations {
			in.Tolerations[i].DeepCopyInto(&out.Tolerations[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		out.TopologySpreadConstraints = make([]corev1.TopologySpreadConstraint, len(in.TopologySpreadConstraints))
		for i := range in.TopologySpreadConstraints {
			in.TopologySpreadConstraints[i].DeepCopyInto(&out.TopologySpreadConstraints[i])
		}
	}
	if in.CrossRegion != nil {
		out.CrossRegion = in.CrossRegion.DeepCopy()
	}
}

func (in *CrossRegionSpec) DeepCopyInto(out *CrossRegionSpec) {
	*out = *in
	if in.Peers != nil {
		out.Peers = make([]CrossRegionPeerSpec, len(in.Peers))
		copy(out.Peers, in.Peers)
	}
}
func (in *CrossRegionSpec) DeepCopy() *CrossRegionSpec {
	if in == nil {
		return nil
	}
	out := new(CrossRegionSpec)
	in.DeepCopyInto(out)
	return out
}
func (in *CrossRegionPeerSpec) DeepCopyInto(out *CrossRegionPeerSpec) { *out = *in }

// ---------- AutoscalingSpec ----------

func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.TargetCPUUtilization != nil {
		v := *in.TargetCPUUtilization
		out.TargetCPUUtilization = &v
	}
	if in.TargetQPS != nil {
		v := *in.TargetQPS
		out.TargetQPS = &v
	}
	if in.TargetStorageUtilization != nil {
		v := *in.TargetStorageUtilization
		out.TargetStorageUtilization = &v
	}
}

// ---------- BackupSpec ----------

func (in *BackupSpec) DeepCopyInto(out *BackupSpec) { *out = *in }

// ---------- SecuritySpec ----------

func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
	if in.APIKeysSecretRef != nil {
		out.APIKeysSecretRef = in.APIKeysSecretRef.DeepCopy()
	}
	if in.JWTSecretRef != nil {
		out.JWTSecretRef = in.JWTSecretRef.DeepCopy()
	}
	if in.TLSSecretRef != nil {
		l := *in.TLSSecretRef
		out.TLSSecretRef = &l
	}
}

// ---------- NebulaClusterSpec ----------

func (in *NebulaClusterSpec) DeepCopyInto(out *NebulaClusterSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Replication.DeepCopyInto(&out.Replication)
	in.AI.DeepCopyInto(&out.AI)
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
	in.Backup.DeepCopyInto(&out.Backup)
	in.Security.DeepCopyInto(&out.Security)

	if in.ImagePullSecrets != nil {
		out.ImagePullSecrets = make([]corev1.LocalObjectReference, len(in.ImagePullSecrets))
		copy(out.ImagePullSecrets, in.ImagePullSecrets)
	}
	if in.Regions != nil {
		out.Regions = make([]RegionSpec, len(in.Regions))
		for i := range in.Regions {
			in.Regions[i].DeepCopyInto(&out.Regions[i])
		}
	}
	if in.MaxUnavailable != nil {
		v := intstr.IntOrString{Type: in.MaxUnavailable.Type, IntVal: in.MaxUnavailable.IntVal, StrVal: in.MaxUnavailable.StrVal}
		out.MaxUnavailable = &v
	}
	if in.ExtraEnv != nil {
		out.ExtraEnv = make([]corev1.EnvVar, len(in.ExtraEnv))
		for i := range in.ExtraEnv {
			in.ExtraEnv[i].DeepCopyInto(&out.ExtraEnv[i])
		}
	}
	if in.PodAnnotations != nil {
		out.PodAnnotations = make(map[string]string, len(in.PodAnnotations))
		for k, v := range in.PodAnnotations {
			out.PodAnnotations[k] = v
		}
	}
	if in.PodLabels != nil {
		out.PodLabels = make(map[string]string, len(in.PodLabels))
		for k, v := range in.PodLabels {
			out.PodLabels[k] = v
		}
	}
}

// ---------- NodeStatus / RebalanceState ----------

func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.LagBytes != nil {
		v := *in.LagBytes
		out.LagBytes = &v
	}
}

func (in *RebalanceState) DeepCopyInto(out *RebalanceState) { *out = *in }

// ---------- NebulaClusterStatus ----------

func (in *NebulaClusterStatus) DeepCopyInto(out *NebulaClusterStatus) {
	*out = *in
	if in.Leader != nil {
		ns := *in.Leader
		in.Leader.DeepCopyInto(&ns)
		out.Leader = &ns
	}
	if in.Followers != nil {
		out.Followers = make([]NodeStatus, len(in.Followers))
		for i := range in.Followers {
			in.Followers[i].DeepCopyInto(&out.Followers[i])
		}
	}
	if in.Rebalance != nil {
		rb := *in.Rebalance
		out.Rebalance = &rb
	}
	if in.LastSnapshotAt != nil {
		t := in.LastSnapshotAt.DeepCopy()
		out.LastSnapshotAt = &t
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// ---------- NebulaCluster (+List) ----------

func (in *NebulaCluster) DeepCopyInto(out *NebulaCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *NebulaCluster) DeepCopy() *NebulaCluster {
	if in == nil {
		return nil
	}
	out := new(NebulaCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *NebulaCluster) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *NebulaClusterList) DeepCopyInto(out *NebulaClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NebulaCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *NebulaClusterList) DeepCopy() *NebulaClusterList {
	if in == nil {
		return nil
	}
	out := new(NebulaClusterList)
	in.DeepCopyInto(out)
	return out
}
func (in *NebulaClusterList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---------- NebulaBucket ----------

func (in *BucketReplicationPolicy) DeepCopyInto(out *BucketReplicationPolicy) { *out = *in }
func (in *BucketIndexingSpec) DeepCopyInto(out *BucketIndexingSpec)           { *out = *in }

func (in *NebulaBucketSpec) DeepCopyInto(out *NebulaBucketSpec) {
	*out = *in
	in.Replication.DeepCopyInto(&out.Replication)
	in.Indexing.DeepCopyInto(&out.Indexing)
	if in.Labels != nil {
		out.Labels = make(map[string]string, len(in.Labels))
		for k, v := range in.Labels {
			out.Labels[k] = v
		}
	}
	if in.ReplicatedTo != nil {
		out.ReplicatedTo = make([]string, len(in.ReplicatedTo))
		copy(out.ReplicatedTo, in.ReplicatedTo)
	}
}

func (in *NebulaBucketStatus) DeepCopyInto(out *NebulaBucketStatus) {
	*out = *in
	if in.TopKeys != nil {
		out.TopKeys = make([]string, len(in.TopKeys))
		copy(out.TopKeys, in.TopKeys)
	}
	if in.LastSeeded != nil {
		t := in.LastSeeded.DeepCopy()
		out.LastSeeded = &t
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *NebulaBucket) DeepCopyInto(out *NebulaBucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *NebulaBucket) DeepCopy() *NebulaBucket {
	if in == nil {
		return nil
	}
	out := new(NebulaBucket)
	in.DeepCopyInto(out)
	return out
}
func (in *NebulaBucket) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *NebulaBucketList) DeepCopyInto(out *NebulaBucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NebulaBucket, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *NebulaBucketList) DeepCopy() *NebulaBucketList {
	if in == nil {
		return nil
	}
	out := new(NebulaBucketList)
	in.DeepCopyInto(out)
	return out
}
func (in *NebulaBucketList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---------- NebulaRebalance ----------

func (in *NodeRef) DeepCopyInto(out *NodeRef) { *out = *in }

func (in *NebulaRebalanceSpec) DeepCopyInto(out *NebulaRebalanceSpec) {
	*out = *in
	if in.Nodes != nil {
		out.Nodes = make([]NodeRef, len(in.Nodes))
		copy(out.Nodes, in.Nodes)
	}
	if in.TargetFollowers != nil {
		v := *in.TargetFollowers
		out.TargetFollowers = &v
	}
	if in.Buckets != nil {
		out.Buckets = make([]string, len(in.Buckets))
		copy(out.Buckets, in.Buckets)
	}
}

func (in *RebalanceStep) DeepCopyInto(out *RebalanceStep) {
	*out = *in
	if in.StartedAt != nil {
		t := in.StartedAt.DeepCopy()
		out.StartedAt = &t
	}
	if in.FinishedAt != nil {
		t := in.FinishedAt.DeepCopy()
		out.FinishedAt = &t
	}
}

func (in *NebulaRebalanceStatus) DeepCopyInto(out *NebulaRebalanceStatus) {
	*out = *in
	if in.StartedAt != nil {
		t := in.StartedAt.DeepCopy()
		out.StartedAt = &t
	}
	if in.CompletedAt != nil {
		t := in.CompletedAt.DeepCopy()
		out.CompletedAt = &t
	}
	if in.Steps != nil {
		out.Steps = make([]RebalanceStep, len(in.Steps))
		for i := range in.Steps {
			in.Steps[i].DeepCopyInto(&out.Steps[i])
		}
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *NebulaRebalance) DeepCopyInto(out *NebulaRebalance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *NebulaRebalance) DeepCopy() *NebulaRebalance {
	if in == nil {
		return nil
	}
	out := new(NebulaRebalance)
	in.DeepCopyInto(out)
	return out
}
func (in *NebulaRebalance) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *NebulaRebalanceList) DeepCopyInto(out *NebulaRebalanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NebulaRebalance, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *NebulaRebalanceList) DeepCopy() *NebulaRebalanceList {
	if in == nil {
		return nil
	}
	out := new(NebulaRebalanceList)
	in.DeepCopyInto(out)
	return out
}
func (in *NebulaRebalanceList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---------- NebulaRegionFailover ----------

func (in *NebulaRegionFailoverSpec) DeepCopyInto(out *NebulaRegionFailoverSpec) { *out = *in }

func (in *NebulaRegionFailoverStatus) DeepCopyInto(out *NebulaRegionFailoverStatus) {
	*out = *in
	if in.StartedAt != nil {
		t := in.StartedAt.DeepCopy()
		out.StartedAt = &t
	}
	if in.CompletedAt != nil {
		t := in.CompletedAt.DeepCopy()
		out.CompletedAt = &t
	}
	if in.Steps != nil {
		out.Steps = make([]RebalanceStep, len(in.Steps))
		for i := range in.Steps {
			in.Steps[i].DeepCopyInto(&out.Steps[i])
		}
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *NebulaRegionFailover) DeepCopyInto(out *NebulaRegionFailover) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *NebulaRegionFailover) DeepCopy() *NebulaRegionFailover {
	if in == nil {
		return nil
	}
	out := new(NebulaRegionFailover)
	in.DeepCopyInto(out)
	return out
}
func (in *NebulaRegionFailover) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *NebulaRegionFailoverList) DeepCopyInto(out *NebulaRegionFailoverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NebulaRegionFailover, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *NebulaRegionFailoverList) DeepCopy() *NebulaRegionFailoverList {
	if in == nil {
		return nil
	}
	out := new(NebulaRegionFailoverList)
	in.DeepCopyInto(out)
	return out
}
func (in *NebulaRegionFailoverList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
