apiVersion: v1
kind: Namespace
metadata:
  name: nebuladb-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebuladb-operator
  namespace: nebuladb-system
  labels: {app.kubernetes.io/name: nebuladb-operator}
spec:
  replicas: 1
  selector:
    matchLabels: {app.kubernetes.io/name: nebuladb-operator}
  template:
    metadata:
      labels: {app.kubernetes.io/name: nebuladb-operator}
    spec:
      serviceAccountName: nebuladb-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile: {type: RuntimeDefault}
      containers:
      - name: manager
        image: ghcr.io/bwalia/nebuladb-operator:dev
        imagePullPolicy: IfNotPresent
        args:
        - --leader-elect=true
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        ports:
        - {name: metrics, containerPort: 8080}
        - {name: healthz, containerPort: 8081}
        livenessProbe:
          httpGet: {path: /healthz, port: healthz}
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet: {path: /readyz, port: healthz}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests: {cpu: 100m, memory: 128Mi}
          limits:   {cpu: 500m, memory: 512Mi}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: {drop: [ALL]}
