{{- if .Values.server.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nebuladb.fullname" . }}
  labels:
    {{- include "nebuladb.server.selectorLabels" . | nindent 4 }}
    {{- include "nebuladb.labels" . | nindent 4 }}
  {{- with .Values.server.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.server.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.server.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.server.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "nebuladb.fullname" $ }}
                port:
                  name: rest
          {{- end }}
    {{- end }}
{{- end -}}
