apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebuladb.fullname" . }}
  labels:
    {{- include "nebuladb.server.selectorLabels" . | nindent 4 }}
    {{- include "nebuladb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "nebuladb.server.selectorLabels" . | nindent 4 }}
  ports:
    - name: rest
      port: {{ .Values.server.service.restPort }}
      targetPort: rest
      protocol: TCP
    - name: grpc
      port: {{ .Values.server.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: pg
      port: {{ .Values.server.service.pgPort }}
      targetPort: pg
      protocol: TCP
